// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfOZ-Cdqhl-znAGa0vgBOh6pMqdz2GWak',
    appId: '1:602200012109:web:188b5773224df1759c7304',
    messagingSenderId: '602200012109',
    projectId: 'luqma-haneya',
    authDomain: 'luqma-haneya.firebaseapp.com',
    storageBucket: 'luqma-haneya.firebasestorage.app',
    measurementId: 'G-E1MVTPH6DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZRC5w3vk8YNNV-X-viw2czuoLyGneXdk',
    appId: '1:602200012109:android:4b1fd31ffd21cf989c7304',
    messagingSenderId: '602200012109',
    projectId: 'luqma-haneya',
    storageBucket: 'luqma-haneya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBubIToBXl_pA6lti-RwnEL5GPumQrgU3I',
    appId: '1:602200012109:ios:af7adc67d9fef7149c7304',
    messagingSenderId: '602200012109',
    projectId: 'luqma-haneya',
    storageBucket: 'luqma-haneya.firebasestorage.app',
    iosBundleId: 'com.luqma.luqmaHaneya',
  );
}
